# Generated by Django 5.2.12 on 2026-04-02 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Duruş Nedeni',
                'verbose_name_plural': 'Duruş Nedenleri',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'İş İstasyonu',
                'verbose_name_plural': 'İş İstasyonları',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Numara')),
                ('product_name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('planned_quantity', models.PositiveIntegerField(verbose_name='Planlanan Adet')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ACTIVE', 'Aktif'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal')], default='DRAFT', max_length=10, verbose_name='Durum')),
                ('assigned_workers', models.ManyToManyField(blank=True, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Atanan İşçiler')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.workstation', verbose_name='İş İstasyonu')),
            ],
            options={
                'verbose_name': 'İş Emri',
                'verbose_name_plural': 'İş Emirleri',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LaborEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('produced_quantity', models.PositiveIntegerField(default=0, verbose_name='Üretilen Adet')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('duration_minutes', models.PositiveIntegerField(default=0, editable=False, verbose_name='Süre (dk)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('COMPLETED', 'Tamamlandı')], default='ACTIVE', max_length=10, verbose_name='Durum')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_entries', to=settings.AUTH_USER_MODEL, verbose_name='İşçi')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_entries', to='production.workorder', verbose_name='İş Emri')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.workstation', verbose_name='İş İstasyonu')),
            ],
            options={
                'verbose_name': 'İşçilik Kaydı',
                'verbose_name_plural': 'İşçilik Kayıtları',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('OPEN', 'Açık'), ('CLOSED', 'Kapalı')], default='OPEN', max_length=10, verbose_name='Durum')),
                ('duration_minutes', models.PositiveIntegerField(default=0, editable=False, verbose_name='Süre (dk)')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.downtimereason', verbose_name='Duruş Nedeni')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtime_records', to=settings.AUTH_USER_MODEL, verbose_name='İşçi')),
                ('labor_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_records', to='production.laborentry', verbose_name='İşçilik Kaydı')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtime_records', to='production.workorder', verbose_name='İş Emri')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.workstation', verbose_name='İş İstasyonu')),
            ],
            options={
                'verbose_name': 'Duruş Kaydı',
                'verbose_name_plural': 'Duruş Kayıtları',
                'ordering': ['-start_time'],
            },
        ),
    ]
